version: "2.1"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456789
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 5s
      interval: 10s
      retries: 10

  app:
    image: customer_api
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8000:8000

volumes:
  pg_data:
