version: "2.1"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456789
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 5s
      interval: 10s
      retries: 10

  app:
    image: customer_api
    build: .
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8000:8000
    volumes:
      - app_static_files:/var/www
    environment:
      PG_USER: postgres
      PG_DB: postgres
      PG_HOST: postgres
      PG_PORT: 5432
      PG_PASSWORD: 123456789
    healthcheck:
      test: ["CMD-SHELL", "netstat -tulpn | grep 8000"]
      timeout: 5s
      interval: 10s
      retries: 10

  nginx:
    image: nginx
    build:
      context: ./nginx
    restart: always
    depends_on:
      app:
        condition: service_healthy
    ports:
      - 80:80
    volumes:
      - app_static_files:/usr/share/nginx/html

volumes:
  pg_data:
  app_static_files:
